= Documentation Technique de l'application DailyBank V2
:toc:
:toc-title: Sommaire

== Équipe
* Nolan JACQUEMONT 
* James SANDALL ROBERTSON 
* Rémy GUIBERT

== 1. Contexte

La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau. Vous travaillerez à partir d’une application existante « Daily Bank » qu’il faudra adapter aux nouveaux besoins de la banque.


== 2. Répartition des tâches 

[options="header,footer"]
|=======================
|version|user     |use case   |cas...                 |   Nolan JACQUEMONT | James SANDALL ROBERTSON | Rémy GUIBERT
|1    |Chef de projet    |CRUD employé  |C| | | F
|1    |chef de projet    |CRUD employé  |R| | | F
|1    |chef de projet    |CRUD employé  |U| | | F
|1    |chef de projet    |CRUD employé  |D| | | F
|1    |Guichetier     | Compte | Créer|| F | 
|1    |Guichetier     | Compte | Créditer/Débiter| F | |
|1    |Guichetier     | Compte | Effectuer un virement| F | | 
|1    |Guichetier     | Compte | Clôturer|| F | 
|2    |Chef d’Agence     | Compte | Débit exceptionnel|| F | 
|2    |Chef d’Agence     | Emprunt | Simuler emprunt|| F | 
|2    |Chef d’Agence     | Emprunt | Simuler assurance|| | F
|2    |Guichetier     | Compte | Relevé PDF| F | | 
|2    |Guichetier     | CRUD Prélèvement | C| F | | 
|2    |Guichetier     | CRUD Prélèvement | R| F | | 
|2    |Guichetier     | CRUD Prélèvement | U| F | | 
|2    |Guichetier     | CRUD Prélèvement | D| F | | 
|2    |Bach     | Prélèvements automatiques | | F | | 
|2    |Bach     | Reléves mensuels | | F | | 

|=======================

== 3. Structure du code

Les packages :

    application
        DailyBank : main() de départ

    application.control
        Contrôleurs de dialogue et accès aux données : gestion des fonctions de l’application

    application.view
        Vues de l’application - fichiers fxml et contrôleurs associés - : gestion des vues uniquement : affichages, contrôle de saisies, …

    application.tools
        Utilitaires pour application.view et application.control

    model.data
        Classes java mappant les table de la BD. Une table ⇒ 1 classe. On peut en ajouter (classes pour jointures, …)

    model.orm
        Classes d’accès physiques à la BD. Une table ⇒ 1 classe offrant différentes méthodes pour accéder à la table : select, insert, delete, update, appel de procédure stockée (elles sont données). On peut en ajouter.

    model.exception
        Classes des exceptions spécifiques d’accès à la BD, levées par les classes de model.orm

== 4 Le paradigme MVC

Si on prend le modèle MVC pour l’application entière, on a :

    Modèle :
        - model.orm : le "vrai" modèle
        - model.data : classes nécessaires pour transporter les données

    Vue :
        application.view : toutes les parties visibles de l’utilisateur, sans accès aux données, sans accès les unes aux autres

    Contrôleur :
        - application.control : classes de contrôle du "déroulement"
            Routage entre fenêtres
            Accès aux données lorsque de besoin
        - application avec la classe DailyBank : main() de lancement de l’application. Et encore, elle ne fait que faire un runApp() sur un contrôleur.

Le reste est juste de "l’aide" :
    - model.exception
    - application.tools



==  5. Le rôle des classes

    application
        - DailyBank : main() de l’application
        - DailyBankState : classe de description du contexte courant de l’application : qui est connecté ? est-il chef d’agence ? à quelle agence bancaire appartient-il ?

    application.control
        - Une classe par fenêtre dite contrôleur de dialogue. Exemple LoginDialog
        - Rôles de chaque classe :
            - A la création : i) construit le Stage java FX de la fenêtre, ii) charge le fichier fxml de la vue et son contrôleur
            - Offre une méthode de démarrage du Dialogue, du type doNomClasseControlDialog(…). Exemple doLoginDialog()
            - Offre des méthodes d’accès aux données, disponibles pour son contrôleur de vue
            - Offre des méthodes d’activation d’autres fenêtres, disponibles pour son contrôleur de vue

    application.view
        - Une classe par fenêtre dite contrôleur de vue ET un fichier fxml associé. Exemple LoginDialogController et logindialog.fxml
        - Un objet d’une telle classe ne connaît de l’application que son contrôleur de dialogue (de application.control)
        - Rôles de chaque classe :
            - Offre une méthode initContext(…) pour être initialisée. Appelée par le contrôleur de dialogue
            - Offre une méthode displayDialog(…) pour afficher la fenêtre. Appelée par le contrôleur de dialogue
            - Gère toutes les réactions aux interactions : saisies, boutons, …
            - Met à jour l’interface lorsque de besoin : griser des boutons, remplir des champs, …
            - Effectue tous les contrôles de surface au niveau de la saisie : valeurs remplies, nombres < 0, …
            - Appelle son contrôleur de vue si besoin d’accéder à des données
            - Appelle son contrôleur de vue si besoin de lancer une autre fonction (fenêtre) de l’application

    model.data
        - Classes java mappant les table de la BD.
            - Une table ⇒ 1 classe. On peut en ajouter (classes pour jointures, …)
        - Servent à échanger les donnes entre model.orm et application.control
        - Ces classes ne définissent aucune méthode qui "fait quelque chose" (calcul, …). Les attributs sont public et une seule méthode toString (). Chaque attribut est un champ de la table.
        - Ces classes ne contiennent que les champs de la BD que l’on souhaite remonter vers l’application.

    model.orm
        - Classes d’accès physiques à la BD.
            - Une table ⇒ 1 classe offrant différentes méthodes pour accéder à la table : select, insert, delete, update, appel de procédure stockée (elles sont données). On peut en ajouter.
        - Chaque classe : effectue une requête SQL, presque la requête qu’on ferait au clavier envoyée au serveur sous forme de String. Ensuite elle emballe le résultat en java (objets de model.data, ArrayList, …).


== 6. Les fonctionnalités

=== Créditer/débiter un compte (par Nolan JACQUEMONT)

Les classes impliquées dans les crédits/débits de compte sont :

- Operation : Cette classe représente un modèle d'opération.
- OperationsManagement : Cette classe charge un contrôleur ("OperationsManagementController") pour l'interface des opérations. Le contrôleur redirige les clics des boutons vers les actions correctes (débit/crédit).
Dans le cas d'un crédit/débit de compte, elle ouvre une nouvelle interface ("OperationsEditorPaneController") pour la saisie des informations de l'opération. Elle récupère ensuite ces saisies pour faire appel à la classe AcessOperation.
- OperationEditorPane : Une classe gérant l'interface de l'ajout d'opération, dans notre cas, il est utilisé pour entrer des informations sur le débit/crédit que nous souhaitons effectuer. Les informations sont ensuite sauvegardées à l'aide de la classe AccessOperation.
- AccessOperation : Cette classe s'occupe d'exécuter des requêtes SQL pour insérer/supprimer/modifier des opérations.

https://github.com/IUT-Blagnac/sae2022-bank-4b01/blob/main/V2/Développement/Documentation/docUtilisateurV2.adoc#enregistrer-un-débit--crédit[Documentation utilisateur correspondante]

=== Effectuer un virement compte à compte (par Nolan JACQUEMONT)

Les classes impliquées dans les virements de compte sont :

- Operation : Cette classe représente un modèle d'opération.
- OperationsManagement : Cette classe charge un contrôleur ("OperationsManagementController") pour l'interface des opérations. Le contrôleur redirige les clics des boutons vers les actions correctes (débit/crédit).
Dans le cas d'un crédit/débit de compte, elle ouvre une nouvelle interface ("OperationsEditorPaneController") pour la saisie des informations de l'opération. Elle récupère ensuite ces saisies pour faire appel à la classe AccessOperation.
- OperationEditorPane : Une classe gérant l'interface de l'ajout d'opération, dans notre cas, il est utilisé pour entrer des informations sur le virement que nous souhaitons effectuer. Les informations sont ensuite sauvegardées à l'aide de la classe AccessOperation.
- AccessOperation : Cette classe s'occupe d'exécuter des requêtes SQL pour insérer/supprimer/modifier des opérations.

https://github.com/IUT-Blagnac/sae2022-bank-4b01/blob/main/V2/Développement/Documentation/docUtilisateurV2.adoc#enregistrer-un-virement[Documentation utilisateur correspondante]

=== Générer le relevé mensuel en pdf (par Nolan JACQUEMONT)

Les classes impliquées dans la génération du relevé mensuel sont :

- ComptesManagement : Cette classe charge un contrôleur ("ComptesManagementController") pour l'interface des comptes. Le contrôleur redirige les clics des boutons vers les actions correctes, ici c'est le bouton "Voir relevé" qui est concerné.
Dans le cas d'un relevé de compte, elle fait appel à la classe AccessCompteCourant.
- AccessCompteCourant : Cette classe s'occupe d'exécuter des requêtes SQL pour récupérer les informations de compte et pour créer le fichier PDF.

https://github.com/IUT-Blagnac/sae2022-bank-4b01/blob/main/V2/Développement/Documentation/docUtilisateurV2.adoc#47-génération-des-relevés-mensuels-au-format-pdf[Documentation utilisateur correspondante]

=== Effectuer prélèvements automatiques (par Nolan JACQUEMONT)

Les classes impliquées dans les prélèvements automatiques sont :

- DailyBankMainFrame : Cette classe charge un contrôleur ("DailyBankMainFrameController") pour l'interface principale. Au lancement de l'application, avant tout affichage, elle appelle la clase "AccessOperation" afin d'effectuer les prélèvements automatiques.
- AccessOperation : Cette classe s'occupe d'exécuter des requêtes SQL pour vérifier les prélèvements du jour et les effectuer si nécessaire.

=== Créer un prélèvement (par Nolan JACQUEMONT)

Les classes impliquées dans la création d'un prélèvement sont :

- Prelevement : Cette classe représente un modèle de prélèvement.
- PrelevementsManagement : Cette classe charge un contrôleur ("PrelevementsManagementController") pour l'interface des prélèvements. Le contrôleur redirige les clics des boutons vers les actions correctes, ici c'est le bouton "Nouveau prélèvement" qui est concerné.
- PrelevementEditorPane : Une classe gérant l'interface de l'ajout de prélèvements, dans notre cas, il est utilisé pour entrer des informations sur le prélèvement que nous souhaitons effectuer. Les informations sont ensuite sauvegardées à l'aide de la classe AccessCompteCourant.
- AccessCompteCourant : Cette classe s'occupe d'exécuter des requêtes SQL pour insérer les informations du prélèvement dans la base de données.

https://github.com/IUT-Blagnac/sae2022-bank-4b01/blob/main/V2/Développement/Documentation/docUtilisateurV2.adoc#ajouter-un-prélèvement[Documentation utilisateur correspondante]

=== Modifier un prélèvement (par Nolan JACQUEMONT)

Les classes impliquées dans la création d'un prélèvement sont :

- Prelevement : Cette classe représente un modèle de prélèvement.
- PrelevementsManagement : Cette classe charge un contrôleur ("PrelevementsManagementController") pour l'interface des prélèvements. Le contrôleur redirige les clics des boutons vers les actions correctes, ici c'est le bouton "Modifier prélèvement" qui est concerné.
- PrelevementEditorPane : Une classe gérant l'interface de la modification de prélèvements, dans notre cas, il est utilisé pour entrer des informations sur le prélèvement que nous souhaitons modifier. Les informations sont ensuite sauvegardées à l'aide de la classe AccessCompteCourant.
- AccessCompteCourant : Cette classe s'occupe d'exécuter des requêtes SQL pour modifier les informations du prélèvement dans la base de données.

https://github.com/IUT-Blagnac/sae2022-bank-4b01/blob/main/V2/Développement/Documentation/docUtilisateurV2.adoc#modifier-un-prélèvement[Documentation utilisateur correspondante]

=== Supprimer un prélèvement (par Nolan JACQUEMONT)

Les classes impliquées dans la création d'un prélèvement sont :

- Prelevement : Cette classe représente un modèle de prélèvement.
- PrelevementsManagement : Cette classe charge un contrôleur ("PrelevementsManagementController") pour l'interface des prélèvements. Le contrôleur redirige les clics des boutons vers les actions correctes, ici c'est le bouton "Supprimer prélèvement" qui est concerné.
- PrelevementEditorPane : Une classe gérant l'interface de la suppression de prélèvements, dans notre cas, il est utilisé pour afficher les informations sur le prélèvement que nous souhaitons supprimer avant de valider.
- AccessCompteCourant : Cette classe s'occupe d'exécuter des requêtes SQL pour supprimer un prélèvement dans la base de données, en modifiant ses informations de telle sorte que celui-ci ne soit jamais réalisé et qu'il puisse être "réactivé" en les modifiant.

https://github.com/IUT-Blagnac/sae2022-bank-4b01/blob/main/V2/Développement/Documentation/docUtilisateurV2.adoc#supprimer-un-prélèvement[Documentation utilisateur correspondante]

=== Créer un compte pour un client (par James ROBERTSON)

Les classes impliquées dans la création d'un compte sont :

- CompteCourant : Cette classe représente un modèle de compte.
- ComptesManagement : Cette classe charge un contrôleur ("ComptesManagementController") pour l'interface des comptes. Le contrôleur redirige les clics des boutons vers les actions correctes.
Dans le cas d'une création de compte, elle ouvre une nouvelle interface (CompteEditorPane) 
- CompteEditorPane : Une classe gérant l'interface de l'éditeur de compte, dans notre cas, il est utilisé pour entrer des informations sur le compte que nous souhaitons ajouter. Les informations sont ensuite sauvegardées à l'aide de la classe AccessCompteCourant
- AccessCompteCourant : Cette classe s'occupe d'exécuter des requêtes SQL pour effectuer des opérations CRUD sur les comptes dans la base de données Oracle.
Une nouvelle instance doit être créée dans chaque domaine où elle est utilisée.


=== Clôturer un compte pour un client (par James ROBERTSON)

Les classes impliquées dans la création d'un compte sont :

- CompteCourant : Cette classe représente un modèle de compte.
- ComptesManagement : Cette classe charge un contrôleur ("ComptesManagementController") pour l'interface des comptes. Le contrôleur redirige les clics des boutons vers les actions correctes.
Dans le cas d'une suppression de compte, on affiche un CompteEditorDialog qui permet à l'utilisateur de confirmer la suppression du compte.  
- CompteEditorPane : Une classe gérant l'interface de l'éditeur de compte, dans notre cas, il est utilisé pour entrer des informations sur le compte que nous souhaitons ajouter. Les informations sont ensuite sauvegardées à l'aide de la classe AccessCompteCourant
- AccessCompteCourant : Cette classe s'occupe d'exécuter des requêtes SQL pour effectuer des opérations CRUD sur les comptes dans la base de données Oracle.
Une nouvelle instance doit être créée dans chaque domaine où elle est utilisée.
Dans ce cas, on utilise une nouvelle fonction 'supprimerCompte' qui envoie une requête SQL permettant de passer le solde du compte à 0 et l'attribut 'estCloture' à 'O'



=== Créer un employé (par Guibert Rémy)

Cette fonctionnalité correspond au use case "Gérer les employés (Crud)".

La partie du diagramme de classe données nécessaire est la table Employe.

https://github.com/IUT-Blagnac/sae2022-bank-4b01/blob/main/V1/D%C3%A9veloppement/Documentation/docUtilisateurV1.adoc#cr%C3%A9er-un-nouvel-employ%C3%A9[Documentation utilisateur correspondante]

Les classes impliquées sont :

- model.data.Employe : représente un employé (nom, prénom, ...).
- model.orm.AccessEmploye : contient les méthodes de gestion des employés sur la base de données (get, insert, ...), envoyer des requêtes SQL.
- application.control.EmployeEditorPane : classe chargeant une vue, l'intègre dans la scène et appel le contrôleur correspondant.
- application.view.EmployeEditorPaneController : contrôleur de la vue FXML "employeeditorpane", s'occupe de tout le fonctionnement de l'interface de création/modification de compte, ici elle sert nottament à valider la saisie et renvoiyer un objet Employe.

Extraits significatifs : la méthode displayDialog(Employe) de EmployeEditorPane prend en paramtre `null` si on souhaite afficher un employé

=== Lire un employé (par Guibert Rémy)

Cette fonctionnalité correspond au use case "Gérer les employés (cRud)".

La partie du diagramme de classe données nécessaire est la table Employe.

https://github.com/IUT-Blagnac/sae2022-bank-4b01/blob/main/V1/D%C3%A9veloppement/Documentation/docUtilisateurV1.adoc#acc%C3%A9der-à-la-page-de-gestion-des-employ%C3%A9s[Documentation utilisateur correspondante]

Les classes impliquées sont :

- model.data.Employe : représente un employé (nom, prénom, ...).
- model.orm.AccessEmploye : contient les méthodes de gestion des employés sur la base de données (get, insert, ...), ici utilisée pour récupérer les employés avec getEmployes() et getEmploye().
- application.control.EmployesManagement : classe chargeant une vue, l'intègre dans la scène, appel le contrôleur correspondant et fait gise d'intermédiaire entre le reste de l'appli et contrôleur, c'est nottamment cette classe qui appel Employe.getEmployes().
- application.view.EmployesManagementController : contrôleur de la vue FXML "employesmanagement", s'occupe de l'initialisation de l'interface et de la vérification des valeurs saisies dans les champs de recherche.

=== Modifier un employé (par Guibert Rémy)

Cette fonctionnalité correspond au use case "Gérer les employés (crUd)".

La partie du diagramme de classe données nécessaire est la table Employe.

https://github.com/IUT-Blagnac/sae2022-bank-4b01/blob/main/V1/D%C3%A9veloppement/Documentation/docUtilisateurV1.adoc#modifier-les-informations-dun-employ%C3%A9[Documentation utilisateur correspondante]

Les classes impliquées sont :

- model.data.Employe : représente un employé (nom, prénom, ...).
- model.orm.AccessEmploye : contient les méthodes de gestion des employés sur la base de données (get, insert, ...), ici utilisée pour mettre à jour les employés avec la méthode updateEmploye().
- application.control.EmployeEditorPane : classe chargeant la vue FXML "employeeditorpane", l'intègre dans la scène et appel le contrôleur correspondant.
- application.view.EmployeEditorPaneController : contrôleur de la vue, s'occupe de tout le fonctionnement de l'interface de modification de compte, ici elle sert nottament à valider la saisie et renvoiyer un objet Employe ou null  si on annule.


=== Supprimer un employé (par Guibert Rémy)

Cette fonctionnalité correspond au use case "Gérer les employés (cruD)".

La partie du diagramme de classe données nécessaire est la table Employe.

https://github.com/IUT-Blagnac/sae2022-bank-4b01/blob/main/V1/D%C3%A9veloppement/Documentation/docUtilisateurV1.adoc#supprimer-un-employ%C3%A9[Documentation utilisateur correspondante]

Les classes impliquées sont :

- model.data.Employe : représente un employé (nom, prénom, ...).
- model.orm.AccessEmploye : contient les méthodes de gestion des employés sur la base de données (get, insert, ...), ici utilisée pour supprimer un employé avec supprimerCompte().
- application.control.EmployesManagement : classe chargeant la vue FXML "employesmanagement", l'intègre dans la scène et appel le contrôleur correspondant.
- application.view.EmployesManagementController : contrôleur de la vue, s'occupe de l'initialisation de l'interface et de la demande de confirmation pour supprimer un compte.


=== Simuler un emprunt (par Robertson James)


Les classes impliquées sont :

- application.control.LoanSimulatorPane : classe chargeant la vue FXML "loansimulatorpane", l'intègre dans la scène et appelle le contrôleur correspondant.
- application.view.LoanSimulatorPaneController : contrôleur de la vue, s'occupe de l'initialisation de l'interface et de la vérification des données entrées.
En cas de données inutilisables (String, chiffres negatifs) les données sont remplacéés par des données acceptables.


=== Simulation d'assurance d'emprunt (par Guibert Rémy)

Cette fonctionnalité correspond au use case "Simuler une assurance d'emprunt".

https://github.com/IUT-Blagnac/sae2022-bank-4b01/blob/main/V2/D%C3%A9veloppement/Documentation/docUtilisateurV2.adoc#45-simulation-dune-assurance-demprunt[Documentation utilisateur V2 correspondante]

Les classes impliquées sont :

- application.control.InsuranceSimulatorPane : classe chargeant la vue FXML "insurancesimulatorpane", l'intègre dans la scène et appel le contrôleur correspondant.
- application.view.InsuranceSimulatorPaneController : contrôleur de la vue, s'occupe de l'initialisation de l'interface et de la vérification des donées entrées

Extraits notable :
Pour savoir si un String est un nombre réel j'ai créer une méthode toDouble(String) qui à la fois converti une chaîne en réel mais en plus permet de savoir si la conversion c'est mal passé en renvoyant -1 (dans le cas où la chaîne ne représente pas un réel).
```java
/** Converti un String en Double
 * @param number	chaîne à convertir
 * @return Le Double correspondant à la chaîne, ou -1 si elle ne correspond pas à un Double
 */
private double toDouble(String number) {
	try {
		return Double.parseDouble(number);
	} catch(Exception e) {
		return -1;
	}
}
```

=== Réaliser un débit exceptionnel (par Robertson James)

Les classes impliquées sont :

- application.control.OperationEditorPan : classe chargeant la vue FXML "operationeditor", l'intègre dans la scène et appelle le contrôleur correspondant.
- application.view.OperationEditorPaneController : contrôleur de la vue, s'occupe de l'initialisation de l'interface et de la vérification des données entrées.
Cette classe a été modifée pour permettre aux Chef d'agences d'ignorer la restriction sur les débits. Une nouvelle procédure a également été crée dans la base de donnée appelée DebitEx qui se comporte comme Debit sans les préconditions.
